# Generated by Django 6.0.5 on 2026-05-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('telefono_tutor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_tutor', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_diagnostico', models.ForeignKey(blank=True, db_column='id_diagnostico', null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.diagnostico')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'historial_clinico',
            },
        ),
    ]
