# Generated by Django 6.0.5 on 2026-05-20 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('prediccion', models.TextField(blank=True, null=True)),
                ('porcentaje_confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mapa_calor', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempo_procesamiento', models.FloatField(blank=True, null=True)),
                ('modelo_ia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resultados_ia',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico_final', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_pdf', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('id_diagnostico', models.ForeignKey(db_column='id_diagnostico', on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.diagnostico')),
            ],
            options={
                'db_table': 'reportes',
            },
        ),
    ]
