# Generated by Django 6.0.5 on 2026-05-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosticos', '0001_initial'),
        ('radiografias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoia',
            name='id_radiografia',
            field=models.ForeignKey(db_column='id_radiografia', on_delete=django.db.models.deletion.CASCADE, to='radiografias.radiografia'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='id_resultado',
            field=models.ForeignKey(db_column='id_resultado', on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.resultadoia'),
        ),
    ]
