# Generated by Django 6.0.5 on 2026-05-20 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radiografia',
            fields=[
                ('id_radiografia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.FileField(upload_to='radiografias/')),
                ('formato', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_procesamiento', models.CharField(default='Pendiente', max_length=50)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'radiografias',
            },
        ),
    ]
